plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.8'
}

group = 'com.example'
version = '0.1.0'
description = 'Учебный проект Event Sourcing Wallet'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-liquibase'
    implementation 'org.springframework.boot:spring-boot-hibernate'
    implementation 'org.hibernate.orm:hibernate-core'
    implementation 'org.springframework:spring-orm'
    implementation 'org.axonframework.extensions.spring:axon-spring-boot-starter:5.3.2'
    runtimeOnly 'org.postgresql:postgresql'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
    options.charSet = 'UTF-8'
}

tasks.named('wrapper') {
    gradleVersion = '9.5.1'
    distributionType = Wrapper.DistributionType.BIN
    distributionSha256Sum = 'bafc141b619ad6350fd975fc903156dd5c151998cc8b058e8c1044ab5f7b031fa'
}
